apiVersion: v1
kind: Pod
metadata:
  name: smarthome-simple-service-pod
  labels:
    app: smarthome-simple-service
spec:
  containers:
    - name: simple-service
      image: cr.selcloud.ru/smart-home/device-service:1
      ports:
        - containerPort: 8080