spring.application.name=integration-service
server.port=8084

weather.api.key=f3304718673143573a03db8b5ec68485
weather.api.baseurl=https://api.openweathermap.org
weather.api.path=/data/2.5/weather
weather.api.lang=ru
weather.api.units=metric