spring.application.name=integration-service
server.port=8084

weather.api.key=${WEATHER_API_KEY}
weather.api.baseurl=${WEATHER_API_BASEURL}
weather.api.path=${WEATHER_API_PATH}
weather.api.lang=ru
weather.api.units=metric